// WARNING: Do NOT edit the input and output ports in this file in a text
// editor if you plan to continue editing the block that represents it in
// the Block Editor! File corruption is VERY likely to occur.

// Copyright (C) 1991-2005 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions
// and other software and tools, and its AMPP partner logic
// functions, and any output files any of the foregoing
// (including device programming or simulation files), and any
// associated documentation or information are expressly subject
// to the terms and conditions of the Altera Program License
// Subscription Agreement, Altera MegaCore Function License
// Agreement, or other applicable license agreement, including,
// without limitation, that your use is for the sole purpose of
// programming logic devices manufactured by Altera and sold by
// Altera or its authorized distributors.  Please refer to the
// applicable agreement for further details.


// Generated by Quartus II Version 5.1 (Build 170 10/3/2005)
// Created on Wed Oct 05 09:31:28 2005

//  Module Declaration
module hvalues
    (
        // {{ALTERA_ARGS_BEGIN}} DO NOT REMOVE THIS LINE!
        sel, h
        // {{ALTERA_ARGS_END}} DO NOT REMOVE THIS LINE!
    );
    // Port Declaration

    // {{ALTERA_IO_BEGIN}} DO NOT REMOVE THIS LINE!
    input [1:0] sel;
    output [2:0] h;
    // {{ALTERA_IO_END}} DO NOT REMOVE THIS LINE!

    reg [2:0]h;

    always @(sel)
    case (sel)
        2'b 00 :
            h = 3'b 111;
        2'b 01 :
            h = 3'b 101;
        2'b 10 :
            h = 3'b 011;
        2'b 11 :
            h = 3'b 001;
    endcase



endmodule
