add wave -noupdate -divider {altera_nios2_qsys_mwb6kynm: top-level ports}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/i_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/i_readdatavalid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/i_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/i_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_write
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_writedata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_irq
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/d_readdatavalid
add wave -noupdate -divider {altera_nios2_qsys_mwb6kynm: base pipeline}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/F_pcb_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/E_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/M_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/W_pcb
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/F_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/E_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/M_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/W_vinst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/F_inst_ram_hit
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/F_iw_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/F_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/F_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_rdprs_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_rdprs_stall_done
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/E_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/M_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/W_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/W_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/W_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/W_wr_data
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/E_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/M_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/F_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/D_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/E_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/M_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/M_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/norm_intr_req
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_status_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_estatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_estatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_bstatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_bstatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_ienable_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_ipending_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_ipending_reg_irq0
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/A_cpuid_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_altera_nios2_qsys_mwb6kynm/E_valid_prior_to_hbreak

configure wave -justifyvalue right
configure wave -signalnamewidth 1
TreeUpdate [SetDefaultTree]
